version: "3.4"

services:

  blackoutland-notfallpunkt-php:
    build: ./conf/php
    container_name: blackoutland-notfallpunkt-php
    hostname: blackoutland-notfallpunkt-php
    volumes:
      - ./www:/var/www
      - ./conf/php/fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./config.json:/config.json
      - ./conf/system.json:/system.json
      - ./temp:/temp
      - ./db:/db
    networks:
      - blackoutland-net
    restart: always
    env_file:
      - .env

  blackoutland-notfallpunkt-nginx:
    image: nginx:1.25.3-alpine3.18
    container_name: blackoutland-nginx
    hostname: blackoutland-nginx
    volumes:
      - ./www:/var/www
      - ./certs:/certs
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - blackoutland-net
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env

networks:
  blackoutland-net:
    external:
      name: blackoutland-net
