version: "3.4"

services:

  notfallpunkt-php:
    build: ./conf/php
    container_name: notfallpunkt-php
    hostname: notfallpunkt-php
    volumes:
      - ./www:/var/www
      - ./conf/php/fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./config.json:/config.json
      - ./conf/system.json:/system.json
      - ./temp:/temp
      - ./db:/db
      - ./fileshare:/fileshare
      - ./tools:/var/tools
    networks:
      - notfallpunkt-net
    restart: always
    env_file:
      - .env

  notfallpunkt-nginx:
    image: nginx:1.25.3-alpine3.18
    container_name: notfallpunkt-nginx
    hostname: notfallpunkt-nginx
    volumes:
      - ./conf/nginx/templates:/etc/nginx/templates
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./certs:/certs
      - ./fileshare:/fileshare
    networks:
      - notfallpunkt-net
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env

  notfallpunkt-memcached:
    image: memcached:bullseye
    container_name: notfallpunkt-memcached
    hostname: notfallpunkt-memcached
    networks:
      - notfallpunkt-net
    restart: always
    env_file:
      - .env

  # Only for development, keep disabled for PROD
  #  notfallpunkt-memcachedadmin:
  #    container_name: notfallpunkt-memcachedadmin
  #    image: 'legacyphp/memcachedadmin:latest'
  #    tty: true
  #    ports:
  #      - '10000:80'
  #    environment:
  #      - 'TZ=UTC'
  #      - 'SERVER=notfallpunkt-memcached:11211'
  #    networks:
  #      - notfallpunkt-net

  notfallpunkt-kiwix:
    container_name: notfallpunkt-kiwix
    hostname: notfallpunkt-kiwix
    ports:
      - 8080:8080
    image: ghcr.io/kiwix/kiwix-serve:latest
    volumes:
      - ./fileshare/kiwix:/data
    command:
      - '*.zim'

  notfallpunkt-ap:
    build: .
    container_name: notfallpunkt-ap
    hostname: notfallpunkt-ap
    network_mode: host
    restart: always
    privileged: true
    volumes:
      - ./certs:/certs
    env_file:
      - .env

networks:
  notfallpunkt-net:
    external:
      name: notfallpunkt-net
